(function(){AdSenseGraphics.POS_TOP_LEFT_=0;AdSenseGraphics.POS_TOP_RIGHT_=1;AdSenseGraphics.POS_BOTTOM_LEFT_=2;AdSenseGraphics.POS_BOTTOM_RIGHT_=3;AdSenseGraphics.X_INTERCEPT_TOP_=0;AdSenseGraphics.X_INTERCEPT_BOTTOM_=1;AdSenseGraphics.Y_INTERCEPT_LEFT_=2;AdSenseGraphics.Y_INTERCEPT_RIGHT_=3;AdSenseGraphics.USER_AGENT_=navigator.userAgent;AdSenseGraphics.IS_OPERA_=typeof opera!="undefined";AdSenseGraphics.IS_IE_=!AdSenseGraphics.IS_OPERA_&&AdSenseGraphics.USER_AGENT_.indexOf("MSIE")!=-1;
AdSenseGraphics.IS_SAFARI_=!AdSenseGraphics.IS_OPERA_&&AdSenseGraphics.USER_AGENT_.indexOf("Safari")!=-1;AdSenseGraphics.S_CURVE_CLASS_NAME_="curve";AdSenseGraphics.ROUNDED_CORNER_BG_CLASS_NAME_="rc_bg";AdSenseGraphics.ROUNDED_CORNER_BORDER_CLASS_NAME_="rc_border";AdSenseGraphics.SIGMOID_FUNCTION_WIDTH=12;AdSenseGraphics.SIGMOID_FUNCTION_OFFSET=6;function AdSenseGraphics(){}AdSenseGraphics.prototype.getPixelLeftX_=function(a){return a};
AdSenseGraphics.prototype.getPixelRightX_=function(a){return a+1};AdSenseGraphics.prototype.getPixelBottomY_=function(a){return a};AdSenseGraphics.prototype.getPixelTopY_=function(a){return a+1};AdSenseGraphics.prototype.computeSigmoid_=function(a,d,b){a=12*a/d-6;return b/(1+Math.exp(a))};AdSenseGraphics.prototype.computeSigmoidInverse_=function(a,d,b){if(a<=0)return d;if(a>=b)return 0;a/=b;a=Math.log((1-a)/a);return d*(a+6)/12};
AdSenseGraphics.prototype.computeCircle_=function(a,d){var b=Math.sqrt(Math.pow(d,2)-Math.pow(a,2));return isNaN(b)?0:b};AdSenseGraphics.prototype.addStyleRule_=function(a,d){if(AdSenseGraphics.IS_IE_)document.styleSheets[0].addRule(a,d);else{var b=document.createElement("style");b.type="text/css";var c=AdSenseGraphics.IS_SAFARI_?"innerText":"innerHTML";b[c]=a+"{"+d+"}";c=document.getElementsByTagName("head")[0];c.appendChild(b)}};
AdSenseGraphics.prototype.createDiv_=function(a,d,b,c,e){var g=document.createElement("div"),h="position:absolute;overflow:hidden;left:";h+=a;h+="px;top:";h+=d;h+="px;width:";h+=b;h+="px;height:";h+=c;h+="px;";if(e!=null){h+="opacity:";h+=e;if(AdSenseGraphics.IS_IE_){h+=";filter: alpha(opacity=";h+=Math.round(e*100);h+=");"}}g.style.cssText=h;return g};
AdSenseGraphics.prototype.getCirclePixelIntercepts_=function(a,d,b){var c=Array(4);c[AdSenseGraphics.Y_INTERCEPT_LEFT_]=this.computeCircle_(this.getPixelLeftX_(a),b);c[AdSenseGraphics.Y_INTERCEPT_RIGHT_]=this.computeCircle_(this.getPixelRightX_(a),b);c[AdSenseGraphics.X_INTERCEPT_BOTTOM_]=this.computeCircle_(this.getPixelBottomY_(d),b);c[AdSenseGraphics.X_INTERCEPT_TOP_]=this.computeCircle_(this.getPixelTopY_(d),b);return c};
AdSenseGraphics.prototype.getSigmoidPixelIntercepts_=function(a,d,b,c){var e=Array(4);e[AdSenseGraphics.Y_INTERCEPT_LEFT_]=this.computeSigmoid_(this.getPixelLeftX_(a),b,c);e[AdSenseGraphics.Y_INTERCEPT_RIGHT_]=this.computeSigmoid_(this.getPixelRightX_(a),b,c);e[AdSenseGraphics.X_INTERCEPT_BOTTOM_]=this.computeSigmoidInverse_(this.getPixelBottomY_(d),b,c);e[AdSenseGraphics.X_INTERCEPT_TOP_]=this.computeSigmoidInverse_(this.getPixelTopY_(d),b,c);return e};
AdSenseGraphics.prototype.getSigmoidAntiAliasOpacity_=function(a,d,b,c){b=this.getSigmoidPixelIntercepts_(a,d,b,c);a=this.getAntiAliasOpacity_(a,d,b);return a==-1?0:a};AdSenseGraphics.prototype.getCircleAntiAliasOpacity_=function(a,d,b,c){b=this.getCirclePixelIntercepts_(a,d,b);a=this.getAntiAliasOpacity_(a,d,b);if(a==-1)return 0;return c?1-a:a};
AdSenseGraphics.prototype.getAntiAliasOpacity_=function(a,d,b){var c=0,e=Array(2),g=Array(2),h=false,l=false,f=false,m=false,j=this.getPixelBottomY_(d);d=this.getPixelTopY_(d);var k=this.getPixelLeftX_(a);a=this.getPixelRightX_(a);if(b[AdSenseGraphics.Y_INTERCEPT_LEFT_]>=j&&b[AdSenseGraphics.Y_INTERCEPT_LEFT_]<d){h=true;e[0]=0;g[0]=b[AdSenseGraphics.Y_INTERCEPT_LEFT_]-j}else if(b[AdSenseGraphics.X_INTERCEPT_TOP_]>=k&&b[AdSenseGraphics.X_INTERCEPT_TOP_]<a){l=true;e[0]=b[AdSenseGraphics.X_INTERCEPT_TOP_]-
k;g[0]=1}if(!l&&!h)return-1;if(b[AdSenseGraphics.Y_INTERCEPT_RIGHT_]>=j&&b[AdSenseGraphics.Y_INTERCEPT_RIGHT_]<d){f=true;e[1]=1;g[1]=b[AdSenseGraphics.Y_INTERCEPT_RIGHT_]-j}else if(b[AdSenseGraphics.X_INTERCEPT_BOTTOM_]>=k&&b[AdSenseGraphics.X_INTERCEPT_BOTTOM_]<a){m=true;e[1]=b[AdSenseGraphics.X_INTERCEPT_BOTTOM_]-k;g[1]=0}if(h&&f){e=g[0]<=g[1]?g[0]:g[1];g=g[0]>g[1]?g[0]:g[1];c=e+(g-e)/2}else if(h&&m)c=g[0]*e[1]/2;else if(l&&f)c=1-(1-e[0])*(1-g[1])/2;else if(l&&m){g=e[0]<=e[1]?e[0]:e[1];e=e[0]>e[1]?
e[0]:e[1];c=g+(e-g)/2}return c};
AdSenseGraphics.prototype.createSigmoidCurve=function(a,d,b,c,e,g){this.addStyleRule_("#"+a.id+" ."+AdSenseGraphics.S_CURVE_CLASS_NAME_+" div","background-color: "+c);a.style.display="none";c=this.createDiv_(0,0,d,b);c.className=AdSenseGraphics.S_CURVE_CLASS_NAME_;for(var h,l=b-1,f,m,j,k=b-1,p=0;p<d;++p){h=l;l=Math.floor(this.computeSigmoid_(p+1,d,b));m=e?p:d-p;f=g?0:b-l;f=this.createDiv_(m,f,1,l);c.appendChild(f);for(var n=l;n<=h;++n){j=this.getSigmoidAntiAliasOpacity_(p,n,d,b);f=g?n:k-n;f=this.createDiv_(m,
f,1,1,j);c.appendChild(f)}}a.appendChild(c);a.style.display=""};
AdSenseGraphics.prototype.applyRoundedCorner=function(a,d,b,c,e,g,h,l){this.addStyleRule_("#"+a.id+" ."+AdSenseGraphics.ROUNDED_CORNER_BG_CLASS_NAME_+" div","background-color: "+c);this.addStyleRule_("#"+a.id+" ."+AdSenseGraphics.ROUNDED_CORNER_BORDER_CLASS_NAME_+" div","background-color: "+e);d+=g;b+=g;var f=a.style;f.display="none";a.innerHTML="";f.position="absolute";f.borderWidth="0px";f.backgroundColor="transparent";e=g+"px solid "+e;var m=l==AdSenseGraphics.POS_TOP_LEFT_||l==AdSenseGraphics.POS_BOTTOM_LEFT_;
l=l==AdSenseGraphics.POS_TOP_LEFT_||l==AdSenseGraphics.POS_TOP_RIGHT_;var j=d-h;if(j>0){var k=m?d-j:0;j=this.createDiv_(k,0,j,b-g);k=j.style;k.backgroundColor=c;l?k.borderTop=e:k.borderBottom=e;a.appendChild(j)}j=b-h;if(j>0){k=l?b-j:0;j=this.createDiv_(0,k,d-g,j);k=j.style;k.backgroundColor=c;m?k.borderLeft=e:k.borderRight=e;a.appendChild(j)}this.createRoundedCorner_(a,d,b,h,g,m,l);f.display=""};
AdSenseGraphics.prototype.createRoundedCorner_=function(a,d,b,c,e,g,h){var l=e>0;e=c-e;d=g?0:d-c;var f=h?0:b-c;b=this.createDiv_(d,f,c,c);b.className=AdSenseGraphics.ROUNDED_CORNER_BG_CLASS_NAME_;var m=this.createDiv_(d,f,c,c);m.className=l?AdSenseGraphics.ROUNDED_CORNER_BORDER_CLASS_NAME_:AdSenseGraphics.ROUNDED_CORNER_BG_CLASS_NAME_;for(var j=e,k=c,p=e,n=c,r,s,t=c-1,q=0;q<c;++q){d=g?t-q:q;j=p;k=n;p=Math.ceil(this.computeCircle_(q+1,e));n=Math.floor(this.computeCircle_(q+1,c));r=l?j:n;f=h?c-r:0;
f=this.createDiv_(d,f,1,r);b.appendChild(f);for(var o=n;o<=k;++o){s=this.getCircleAntiAliasOpacity_(q,o,c,false);f=h?t-o:o;f=this.createDiv_(d,f,1,1,s);m.appendChild(f)}if(l){k=n-r;if(k>0){f=h?c-r-k:r;f=this.createDiv_(d,f,1,k);m.appendChild(f)}for(o=p-1;o<j;++o){s=this.getCircleAntiAliasOpacity_(q,o,e,true);f=h?t-o:o;f=this.createDiv_(d,f,1,1,s);m.appendChild(f)}}}a.appendChild(b);a.appendChild(m)};var asg=new AdSenseGraphics;if(typeof window.rcl!="undefined")for(var rc,i=0;i<rcl.length;i++){rc=rcl[i];asg.applyRoundedCorner(document.getElementById(rc[0]),rc[1],rc[2],rc[3],rc[4],rc[5],rc[6],rc[7])}typeof window.sc!="undefined"&&asg.createSigmoidCurve(document.getElementById(sc[0]),sc[1],sc[2],sc[3],sc[4],sc[5]);})()
